version: '3.8'
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
    ports:
      - "3306:3306"
    
    restart: always